baseURL = 'https://slepox.github.io/'
languageCode = 'en-us'
title = "sLog"
theme = 'LoveIt'
hasCJKLanguage = true

[author]
  name = "slepox"
  email = "slepox@gmail.com"
  link = "https://slepox.github.io"

