baseURL = 'https://slepox.github.io/'
languageCode = 'en'
title = "sLog"
theme = 'LoveIt'
hasCJKLanguage = true

[author]
  name = "slepox"
  email = "slepox@gmail.com"
  link = "https://slepox.github.io"

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/slepox/slepox.github.io"
  dateFormat = "2006-01-02"

  [params.header]
    [params.header.title]
      name = "North of SKY"
  
  [params.footer]
    since = 2023

  [params.home]
    [params.home.profile]
      enable = true
      gravatarEmail = "slepox@gmail.com"
      title = "North of SKY"
      subtitle = "Every star has a desnity"
      social = true
  
  [params.social]
    GitHub = "slepox"
    Linkedin = "slepox"
    Twitter = "slepox"
    Instagram = "slepox"
    Facebook = "slepox"
    
